export const boards: any[] = [
  {
    id: "applied",
    title: "Applied",
    items: [
      {
        id: "1",
        name: "Lisa Manie",
        email: "lisamarie@gmail.com",
        role: "Marketing Coordinator",
        date: new Date(),
        attachmentsCount: 2,
        emailsCount: 2,
        avatar: "https://avatars.githubusercontent.com/u/8983207",
        progress: 20,
      },
      {
        id: "2",
        name: "John Doe",
        email: "johndoe@gmail.com",
        role: "Software Engineer",
        date: new Date(),
        attachmentsCount: 1,
        emailsCount: 1,
        avatar: "https://avatars.githubusercontent.com/u/1234567",
        progress: 30,
      },
      {
        id: "3",
        name: "Jane Smith",
        email: "janesmith@gmail.com",
        role: "Product Manager",
        date: new Date(),
        attachmentsCount: 3,
        emailsCount: 2,
        avatar: "https://avatars.githubusercontent.com/u/7654321",
        progress: 40,
      },
    ],
  },
  {
    id: "inreview",
    title: "In Review",
    items: [
      {
        id: "4",
        name: "Alice Johnson",
        email: "alicej@gmail.com",
        role: "UX Designer",
        date: new Date(),
        attachmentsCount: 2,
        emailsCount: 1,
        avatar: "https://avatars.githubusercontent.com/u/1122334",
        progress: 50,
      },
      {
        id: "5",
        name: "Bob Brown",
        email: "bobbrown@gmail.com",
        role: "Data Analyst",
        date: new Date(),
        attachmentsCount: 1,
        emailsCount: 3,
        avatar: "https://avatars.githubusercontent.com/u/2233445",
        progress: 60,
      },
      {
        id: "6",
        name: "Charlie Davis",
        email: "charlied@gmail.com",
        role: "Frontend Developer",
        date: new Date(),
        attachmentsCount: 2,
        emailsCount: 2,
        avatar: "https://avatars.githubusercontent.com/u/3344556",
        progress: 70,
      },
    ],
  },
  {
    id: "interview",
    title: "Interview",
    items: [
      {
        id: "7",
        name: "David Wilson",
        email: "davidw@gmail.com",
        role: "Backend Developer",
        date: new Date(),
        attachmentsCount: 1,
        emailsCount: 2,
        avatar: "https://avatars.githubusercontent.com/u/4455667",
        progress: 80,
      },
      {
        id: "8",
        name: "Eva Green",
        email: "evagreen@gmail.com",
        role: "DevOps Engineer",
        date: new Date(),
        attachmentsCount: 3,
        emailsCount: 1,
        avatar: "https://avatars.githubusercontent.com/u/5566778",
        progress: 90,
      },
      {
        id: "9",
        name: "Frank White",
        email: "frankw@gmail.com",
        role: "Full Stack Developer",
        date: new Date(),
        attachmentsCount: 2,
        emailsCount: 2,
        avatar: "https://avatars.githubusercontent.com/u/6677889",
        progress: 10,
      },
    ],
  },
  {
    id: "hire",
    title: "Hire",
    items: [
      {
        id: "10",
        name: "Grace Lee",
        email: "gracelee@gmail.com",
        role: "Mobile Developer",
        date: new Date(),
        attachmentsCount: 1,
        emailsCount: 1,
        avatar: "https://avatars.githubusercontent.com/u/7788990",
        progress: 20,
      },
      {
        id: "11",
        name: "Henry Clark",
        email: "henryc@gmail.com",
        role: "QA Engineer",
        date: new Date(),
        attachmentsCount: 2,
        emailsCount: 2,
        avatar: "https://avatars.githubusercontent.com/u/8899001",
        progress: 30,
      },
      {
        id: "12",
        name: "Ivy Adams",
        email: "ivya@gmail.com",
        role: "Technical Writer",
        date: new Date(),
        attachmentsCount: 1,
        emailsCount: 1,
        avatar: "https://avatars.githubusercontent.com/u/9900112",
        progress: 40,
      },
    ],
  },
  {
    id: "rejected",
    title: "Rejected",
    items: [
      {
        id: "13",
        name: "Jack Evans",
        email: "jacke@gmail.com",
        role: "System Administrator",
        date: new Date(),
        attachmentsCount: 1,
        emailsCount: 1,
        avatar: "https://avatars.githubusercontent.com/u/1122334",
        progress: 50,
      },
      {
        id: "14",
        name: "Karen Hill",
        email: "karenh@gmail.com",
        role: "Network Engineer",
        date: new Date(),
        attachmentsCount: 2,
        emailsCount: 2,
        avatar: "https://avatars.githubusercontent.com/u/2233445",
        progress: 60,
      },
      {
        id: "15",
        name: "Leo King",
        email: "leok@gmail.com",
        role: "Security Specialist",
        date: new Date(),
        attachmentsCount: 1,
        emailsCount: 1,
        avatar: "https://avatars.githubusercontent.com/u/3344556",
        progress: 70,
      },
    ],
  },
];
