export const schedules = [
  {
    title: "Finance Meeting",
    date: "2025-01-04T10:25:03.413Z",
    location: "Training Room 2",
    participant: "HR Team",
    department: "Finance",
    note: "Please arrive 10 minutes early for setup.",
  },
  {
    title: "Customer Support Meeting",
    date: "2025-01-11T05:14:10.317Z",
    location: "Main Office Conference Room B",
    participant: "Sales Team",
    department: "Customer Support",
    note: "Please bring your laptops for the presentation.",
  },
  {
    title: "Administration Meeting",
    date: "2025-01-24T21:41:53.341Z",
    location: "Main Office Conference Room B",
    participant: "Sales Team",
    department: "Administration",
    note: "Lunch will be provided after the meeting.",
  },
  {
    title: "Legal Meeting",
    date: "2025-01-27T03:58:18.536Z",
    location: "Virtual - Microsoft Teams",
    participant: "Legal Team",
    department: "Legal",
    note: "Dress code: Business casual.",
  },
  {
    title: "Marketing Meeting",
    date: "2025-01-27T06:14:57.883Z",
    location: "Training Room 2",
    participant: "Customer Support Team",
    department: "Marketing",
    note: "Dress code: Business casual.",
  },
  {
    title: "Marketing Meeting",
    date: "2025-02-03T19:52:09.835Z",
    location: "Virtual - Zoom Platform",
    participant: "HR Team",
    department: "Marketing",
    note: "Pre-meeting materials have been shared via email.",
  },
  {
    title: "Sales Meeting",
    date: "2025-02-13T21:49:21.025Z",
    location: "Training Room 1",
    participant: "Marketing Team",
    department: "Sales",
    note: "This is a mandatory meeting for all team members.",
  },
  {
    title: "Engineering Meeting",
    date: "2025-02-17T09:36:37.469Z",
    location: "Main Office Conference Room A",
    participant: "Sales Team",
    department: "Engineering",
    note: "Please bring your laptops for the presentation.",
  },
  {
    title: "Sales Meeting",
    date: "2025-02-24T02:17:13.796Z",
    location: "Virtual - Microsoft Teams",
    participant: "Administration Team",
    department: "Sales",
    note: "Pre-meeting materials have been shared via email.",
  },
  {
    title: "Human Resources Meeting",
    date: "2025-02-27T09:03:23.483Z",
    location: "Cafeteria Meeting Area",
    participant: "Finance Team",
    department: "Human Resources",
    note: "Please arrive 10 minutes early for setup.",
  },
  {
    title: "Customer Support Meeting",
    date: "2025-02-28T14:46:11.624Z",
    location: "Training Room 2",
    participant: "HR Team",
    department: "Customer Support",
    note: "Lunch will be provided after the meeting.",
  },
  {
    title: "Human Resources Meeting",
    date: "2025-03-01T00:18:40.521Z",
    location: "Main Office Conference Room A",
    participant: "Customer Support Team",
    department: "Human Resources",
    note: "Ensure all reports are submitted before the meeting.",
  },
  {
    title: "Sales Meeting",
    date: "2025-03-08T19:34:14.373Z",
    location: "Virtual - Microsoft Teams",
    participant: "Engineering Team",
    department: "Sales",
    note: "Pre-meeting materials have been shared via email.",
  },
  {
    title: "Legal Meeting",
    date: "2025-03-08T22:54:28.650Z",
    location: "Virtual - Zoom Platform",
    participant: "Legal Team",
    department: "Legal",
    note: "Dress code: Business casual.",
  },
  {
    title: "Customer Support Meeting",
    date: "2025-03-11T04:29:08.750Z",
    location: "Virtual - Microsoft Teams",
    participant: "Marketing Team",
    department: "Customer Support",
    note: "Ensure all reports are submitted before the meeting.",
  },
  {
    title: "Administration Meeting",
    date: "2025-03-15T01:01:14.754Z",
    location: "Cafeteria Meeting Area",
    participant: "Sales Team",
    department: "Administration",
    note: "Ensure all reports are submitted before the meeting.",
  },
  {
    title: "Legal Meeting",
    date: "2025-03-16T23:51:26.031Z",
    location: "Virtual - Microsoft Teams",
    participant: "HR Team",
    department: "Legal",
    note: "Please arrive 10 minutes early for setup.",
  },
  {
    title: "Administration Meeting",
    date: "2025-03-23T21:20:47.576Z",
    location: "Training Room 1",
    participant: "Engineering Team",
    department: "Administration",
    note: "This is a mandatory meeting for all team members.",
  },
  {
    title: "Marketing Meeting",
    date: "2025-03-25T12:37:38.221Z",
    location: "Training Room 2",
    participant: "Marketing Team",
    department: "Marketing",
    note: "Ensure all reports are submitted before the meeting.",
  },
  {
    title: "Human Resources Meeting",
    date: "2025-03-29T02:42:58.963Z",
    location: "Main Office Conference Room B",
    participant: "Legal Team",
    department: "Human Resources",
    note: "This is a mandatory meeting for all team members.",
  },
];
